import { BRAND } from "./brand.js";
import type { DesignSystem, DimensionToken } from "./schema.js";
import { countTokens } from "./schema.js";

/**
 * Exports. Both formats are available on every plan, always — a design system
 * you cannot walk away with is not yours.
 */

type DtcgToken = { $type: string; $value: string; $description?: string };
type DtcgGroup = { [key: string]: DtcgToken | DtcgGroup };

function group(
  record: Record<string, DimensionToken>,
  $type: string,
): DtcgGroup | undefined {
  const entries = Object.entries(record);
  if (entries.length === 0) return undefined;
  const out: DtcgGroup = {};
  for (const [name, token] of entries) {
    out[name] = {
      $type,
      $value: token.value,
      ...(token.usage ? { $description: token.usage } : {}),
    };
  }
  return out;
}

/** W3C Design Tokens Community Group format — the portable one. */
export function toW3CTokens(system: DesignSystem): DtcgGroup {
  const t = system.tokens;
  const out: DtcgGroup = {};
  const put = (key: string, value: DtcgGroup | undefined) => {
    if (value) out[key] = value;
  };

  put("color", group(t.color, "color"));
  put("spacing", group(t.spacing, "dimension"));
  put("radius", group(t.radius, "dimension"));
  put("shadow", group(t.shadow, "shadow"));
  put("border", group(t.border, "dimension"));

  const typography: DtcgGroup = {};
  const putType = (key: string, value: DtcgGroup | undefined) => {
    if (value) typography[key] = value;
  };
  putType("family", group(t.typography.families, "fontFamily"));
  putType("size", group(t.typography.sizes, "dimension"));
  putType("weight", group(t.typography.weights, "fontWeight"));
  putType("lineHeight", group(t.typography.lineHeights, "number"));
  putType("letterSpacing", group(t.typography.letterSpacing, "dimension"));
  if (Object.keys(typography).length > 0) out["typography"] = typography;

  return out;
}

function table(title: string, record: Record<string, DimensionToken>): string[] {
  const entries = Object.entries(record);
  if (entries.length === 0) return [];
  const lines = [`### ${title}`, "", "| Token | Value | Usage |", "| --- | --- | --- |"];
  for (const [name, token] of entries) {
    lines.push(`| \`${name}\` | \`${token.value}\` | ${token.usage ?? ""} |`);
  }
  lines.push("");
  return lines;
}

/** A DESIGN.md a human would actually keep. */
export function toDesignMd(system: DesignSystem): string {
  const t = system.tokens;
  const lines: string[] = [
    `# ${system.meta.name} — design system`,
    "",
    `${countTokens(system)} tokens · extracted from ${system.meta.source}` +
      (system.meta.extractedAt ? ` · ${system.meta.extractedAt}` : ""),
    "",
    `> Generated by ${BRAND.name}. Every visual value below is canonical —`,
    "> never invent a colour, size, spacing step, or radius that is not here.",
    "",
    "## Tokens",
    "",
  ];

  if (Object.keys(t.color).length > 0) {
    lines.push("### Color", "", "| Token | Value | Usage |", "| --- | --- | --- |");
    for (const [name, token] of Object.entries(t.color)) {
      lines.push(`| \`${name}\` | \`${token.value}\` | ${token.usage ?? ""} |`);
    }
    lines.push("");
  }
  lines.push(...table("Font family", t.typography.families));
  lines.push(...table("Font size", t.typography.sizes));
  lines.push(...table("Font weight", t.typography.weights));
  lines.push(...table("Line height", t.typography.lineHeights));
  lines.push(...table("Letter spacing", t.typography.letterSpacing));
  lines.push(...table("Spacing", t.spacing));
  lines.push(...table("Radius", t.radius));
  lines.push(...table("Shadow", t.shadow));
  lines.push(...table("Border", t.border));

  if (system.components.length > 0) {
    lines.push("## Components", "");
    for (const c of system.components) {
      lines.push(`### ${c.name}`, "");
      if (c.description) lines.push(c.description, "");
      if (c.anatomy) lines.push(`**Anatomy** — ${c.anatomy}`, "");
      if (c.variants.length) lines.push(`**Variants** — ${c.variants.join(", ")}`, "");
      if (c.tokensUsed.length) {
        lines.push(`**Tokens** — ${c.tokensUsed.map((x) => `\`${x}\``).join(", ")}`, "");
      }
      const states = c.preview?.states ?? [];
      if (states.length > 0) {
        lines.push("| State | CSS |", "| --- | --- |");
        for (const state of states) {
          const css = Object.entries(state.styles)
            .map(([property, value]) => `${property}: ${value}`)
            .join("; ");
          lines.push(`| \`${state.name}\` | \`${css}\` |`);
        }
        lines.push("");
      }
      for (const d of c.dos) lines.push(`- ✅ ${d}`);
      for (const d of c.donts) lines.push(`- ❌ ${d}`);
      if (c.dos.length || c.donts.length) lines.push("");
    }
  }

  if (system.rules.length > 0) {
    lines.push("## Rules", "");
    for (const rule of system.rules) {
      lines.push(`- **${rule.severity === "must" ? "Must" : "Should"}** — ${rule.statement}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
